echo "===== SMARTBUILD FORENSICS ($1) ====="
echo "pwd:                $PWD"
echo "commit:             $(git --no-optional-locks ls-files -s "$PWD" | git --no-optional-locks hash-object --stdin)"
echo "diff-sha:           $(git --no-optional-locks diff --no-color -- HEAD "$PWD" | shasum -a 256 2>/dev/null || git --no-optional-locks diff --no-color -- HEAD "$PWD" | sha256sum)"
echo "diff-bytes:         $(git --no-optional-locks diff --no-color -- HEAD "$PWD" | wc -c)"
echo "untracked:          [$(git --no-optional-locks ls-files --others --exclude-standard "$PWD" | tr '\n' ' ')]"
echo "dockerfile_content: $(sha256sum Dockerfile 2>/dev/null || shasum -a 256 Dockerfile)"
echo "eol:                $(git ls-files --eol Dockerfile)"
echo "gitcfg:             [$(git config -l | grep -Ei 'autocrlf|core.eol|filter\.' | tr '\n' ' ')]"
echo "status:             [$(git status --short | tr '\n' '|')]"
echo "submodule dir:      $(ls -la okteto-destroy-fail 2>&1 | head -2 | tr '\n' '|')"
echo "git version:        $(git --version)"
echo "uid/owner:          euid=$(id -u) repo_owner=$(stat -c %u . 2>/dev/null || stat -f %u .)"
echo "===== END FORENSICS ====="
