apiVersion: v1
kind: Pod
metadata:
  name: delayed-start-pod
spec:
  containers:
  - name: delayed-container
    image: python:3.8-alpine
    env:
    - name: POD_CREATION_TIMESTAMP
      valueFrom:
        fieldRef:
          fieldPath: metadata.creationTimestamp
    command: ["python", "-c"]
    args:
    - |
      import os
      import sys
      from datetime import datetime, timedelta

      # Get the Pod creation timestamp from the environment variable
      pod_creation_time_str = os.environ.get("POD_CREATION_TIMESTAMP")
      # Parse the timestamp into a datetime object
      pod_creation_time = datetime.strptime(pod_creation_time_str, "%Y-%m-%dT%H:%M:%SZ")
      # Calculate the time when the Pod should start
      start_time = pod_creation_time + timedelta(minutes=5)
      # Get the current time in UTC
      now = datetime.utcnow()

      if now < start_time:
          print("Not yet time to start")
          sys.exit(1)
      else:
          print("Starting the application")
          # Replace the following line with your application start command
          sys.exit(0)