services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_USERNAME=okteto
      - MONGODB_PASSWORD=mongodb123
      - MONGODB_DATABASE=okteto
      - MONGODB_HOST=mongodb
    ports:
      - 8080
    command: yarn start