name: Build image in Okteto

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Okteto context
        uses: okteto/context@latest
        with:
          url: ${{ secrets.OKTETO_URL }}
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Build service-a
        uses: okteto/build@latest
        with:
          path: service-a
          buildargs: TEST_VALUE=r6b2y9jc4n
