on: 
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Context
      uses: okteto/context@ifbyol/test-action-cli-beta
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        url: ${{ secrets.OKTETO_URL }}
    - name: Test
      uses: okteto/test@ifbyol/test-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        namespace: ifbyol-okteto-admin
        file: okteto.yaml
