on: 
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Set kubeconfig
      run: echo "KUBECONFIG=/github/home/.kube/config" >> $GITHUB_ENV

    - name: Context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        url: ${{ secrets.OKTETO_URL }}
      env:
        KUBECONFIG: /github/home/.kube/config

    - name: Set kubeconfig
      run: cd ${RUNNER_TEMP}/_github_home/.kube